//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberiYonetici_TEIAS.WebServiceTelefonRehberi {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceTelefonRehberi.WebServiceRehber2Soap")]
    public interface WebServiceRehber2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsimAra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IsimAra(string ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsimAra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IsimAraAsync(string ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BolumAra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BolumAra(string BolumAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BolumAra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BolumAraAsync(string BolumAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrafoAra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TrafoAra(string TrafoAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrafoAra", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TrafoAraAsync(string TrafoAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VeriGoster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VeriGoster();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VeriGoster", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> VeriGosterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VeriGoster2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VeriGoster2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VeriGoster2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> VeriGoster2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiEkle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet KisiEkle(string AdSoyad, string Dahili1, string Dahili2, string BolumAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> KisiEkleAsync(string AdSoyad, string Dahili1, string Dahili2, string BolumAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiSil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int KisiSil(int dahiliID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiSil", ReplyAction="*")]
        System.Threading.Tasks.Task<int> KisiSilAsync(int dahiliID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiGuncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet KisiGuncelle(string adSoyad, string dahili1, string dahili2, string bolumAdi, int dahiliID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> KisiGuncelleAsync(string adSoyad, string dahili1, string dahili2, string bolumAdi, int dahiliID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrafoEkle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TrafoEkle(string Isim, string TelefonNo, string KodNo, string PaxNo, string BirimAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrafoEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TrafoEkleAsync(string Isim, string TelefonNo, string KodNo, string PaxNo, string BirimAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrafoSil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int TrafoSil(int trafoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrafoSil", ReplyAction="*")]
        System.Threading.Tasks.Task<int> TrafoSilAsync(int trafoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrafoGuncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TrafoGuncelle(string isim, string telefonNo, string kodNo, string paxNo, string birimAdi, int trafoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrafoGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TrafoGuncelleAsync(string isim, string telefonNo, string kodNo, string paxNo, string birimAdi, int trafoID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceRehber2SoapChannel : TelefonRehberiYonetici_TEIAS.WebServiceTelefonRehberi.WebServiceRehber2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceRehber2SoapClient : System.ServiceModel.ClientBase<TelefonRehberiYonetici_TEIAS.WebServiceTelefonRehberi.WebServiceRehber2Soap>, TelefonRehberiYonetici_TEIAS.WebServiceTelefonRehberi.WebServiceRehber2Soap {
        
        public WebServiceRehber2SoapClient() {
        }
        
        public WebServiceRehber2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceRehber2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceRehber2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceRehber2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet IsimAra(string ad) {
            return base.Channel.IsimAra(ad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IsimAraAsync(string ad) {
            return base.Channel.IsimAraAsync(ad);
        }
        
        public System.Data.DataSet BolumAra(string BolumAdi) {
            return base.Channel.BolumAra(BolumAdi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BolumAraAsync(string BolumAdi) {
            return base.Channel.BolumAraAsync(BolumAdi);
        }
        
        public System.Data.DataSet TrafoAra(string TrafoAdi) {
            return base.Channel.TrafoAra(TrafoAdi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TrafoAraAsync(string TrafoAdi) {
            return base.Channel.TrafoAraAsync(TrafoAdi);
        }
        
        public System.Data.DataSet VeriGoster() {
            return base.Channel.VeriGoster();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> VeriGosterAsync() {
            return base.Channel.VeriGosterAsync();
        }
        
        public System.Data.DataSet VeriGoster2() {
            return base.Channel.VeriGoster2();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> VeriGoster2Async() {
            return base.Channel.VeriGoster2Async();
        }
        
        public System.Data.DataSet KisiEkle(string AdSoyad, string Dahili1, string Dahili2, string BolumAdi) {
            return base.Channel.KisiEkle(AdSoyad, Dahili1, Dahili2, BolumAdi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> KisiEkleAsync(string AdSoyad, string Dahili1, string Dahili2, string BolumAdi) {
            return base.Channel.KisiEkleAsync(AdSoyad, Dahili1, Dahili2, BolumAdi);
        }
        
        public int KisiSil(int dahiliID) {
            return base.Channel.KisiSil(dahiliID);
        }
        
        public System.Threading.Tasks.Task<int> KisiSilAsync(int dahiliID) {
            return base.Channel.KisiSilAsync(dahiliID);
        }
        
        public System.Data.DataSet KisiGuncelle(string adSoyad, string dahili1, string dahili2, string bolumAdi, int dahiliID) {
            return base.Channel.KisiGuncelle(adSoyad, dahili1, dahili2, bolumAdi, dahiliID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> KisiGuncelleAsync(string adSoyad, string dahili1, string dahili2, string bolumAdi, int dahiliID) {
            return base.Channel.KisiGuncelleAsync(adSoyad, dahili1, dahili2, bolumAdi, dahiliID);
        }
        
        public System.Data.DataSet TrafoEkle(string Isim, string TelefonNo, string KodNo, string PaxNo, string BirimAdi) {
            return base.Channel.TrafoEkle(Isim, TelefonNo, KodNo, PaxNo, BirimAdi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TrafoEkleAsync(string Isim, string TelefonNo, string KodNo, string PaxNo, string BirimAdi) {
            return base.Channel.TrafoEkleAsync(Isim, TelefonNo, KodNo, PaxNo, BirimAdi);
        }
        
        public int TrafoSil(int trafoID) {
            return base.Channel.TrafoSil(trafoID);
        }
        
        public System.Threading.Tasks.Task<int> TrafoSilAsync(int trafoID) {
            return base.Channel.TrafoSilAsync(trafoID);
        }
        
        public System.Data.DataSet TrafoGuncelle(string isim, string telefonNo, string kodNo, string paxNo, string birimAdi, int trafoID) {
            return base.Channel.TrafoGuncelle(isim, telefonNo, kodNo, paxNo, birimAdi, trafoID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TrafoGuncelleAsync(string isim, string telefonNo, string kodNo, string paxNo, string birimAdi, int trafoID) {
            return base.Channel.TrafoGuncelleAsync(isim, telefonNo, kodNo, paxNo, birimAdi, trafoID);
        }
    }
}
